global:
  env:
    'LOGGING__LOGLEVEL__DEFAULT': 'Error'
    'LOGGING__LOGLEVEL__AWP': 'Information'
    'ASPNETCORE_ENVIRONMENT': 'Development'
    'Env': 'prod'
    'AppBaseUrl': 'https://prod-cc-str-dss.apps.advsol-ams.3j6z.p1.openshiftapps.com'

nameOverride: cc-str-dss-prod
fullnameOverride: cc-str-dss-prod

route:
  host: prod-cc-str-dss.apps.advsol-ams.3j6z.p1.openshiftapps.com
  baseService: cc-str-dss-prod

frontend:
  enabled: true
  replicaCount: 3
  nameOverride: cc-str-dss-prod-frontend
  fullnameOverride: cc-str-dss-prod-frontend

  resources:
  limits:
    cpu: 50m
    memory: 100Mi
  requests:
    cpu: 20m
    memory: 50Mi

  env:
    'SSO_CLIENT': 'advsol-public'
    'SSO_REALM': 'master'
    'SSO_HOST': 'https://keycloak-b07b69-dev.apps.advsol-ams.3j6z.p1.openshiftapps.com/auth'
    'APP_ENV': 'prod'

backend:
  enabled: true
  replicaCount: 3
  nameOverride: cc-str-dss-prod-backend
  fullnameOverride: cc-str-dss-prod-backend

  postgresSecret: cc-str-dss-prod-postgres

  resources:
    limits:
      cpu: 1500m
      memory: 1500Mi
    requests:
      cpu: 20m
      memory: 1100Mi

  env:
    'JWT__Authority': 'https://keycloak-b07b69-dev.apps.advsol-ams.3j6z.p1.openshiftapps.com/auth/realms/master'
    'JWT__Audience': 'advsol-public'
    'DB_HOST': 'cc-str-dss-prod-postgres'
    'DB_USER': 'postgres'
    'DB_NAME': 'postgres'

postgresql:
  nameOverride: cc-str-dss-prod-postgres
  fullnameOverride: cc-str-dss-prod-postgres