primary:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  persistence:
    size: 1Gi
readReplicas:
  persistence:
    size: 1Gi
nameOverride: cc-str-dss-test-postgres
fullnameOverride: cc-str-dss-test-postgres