name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
  - name: Install asdf
    uses: asdf-vm/actions/setup@8b8467c5522bb0aea4977082037e4f2956d67e52

  - name: Cache tools
    uses: actions/cache@67b839edb68371cc5014f6cea11c9aa77238de78
    with:
      path: /home/runner/.asdf
      key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}

  - name: Install required tools
    run: |
      cat .tool-versions | cut -f 1 -d ' ' | xargs -n 1 asdf plugin-add || true
      asdf plugin-add docker-compose https://github.com/virtualstaticvoid/asdf-docker-compose.git || true
      asdf plugin-update --all
      asdf install
      asdf reshim
    shell: bash

  - name: Install python tools
    run: |
      pip install -r requirements.txt
      asdf reshim
    shell: bash
